process TRIGGER_MITOGENOME {
    tag "trigger_mitogenome"

    input:
    val all_samples     // Used to trigger this process after all samples are collected
    path mito_launcher  // ${params.mitogenome_nfcore_dir}/nextflow_run.sh

    output:
    path "run_*.sh", emit: mito_run_script


script:
def input_pattern = "${params.outdir}/draftgenomes/*/fastp/*.fastq.gz"

// The launcher body is a verbatim copy of the mito pipeline's own
// nextflow_run.sh: only the run-specific values are supplied here, as the OG_*
// overrides that script reads. Nothing about the mito run is duplicated in this
// module, so launcher changes are made once, in the mito repo, and the next
// triggered run picks them up. `mito_launcher` is staged as an input so that a
// change to it invalidates this task's cache.
"""
# Generate timestamp once
TIMESTAMP=\$(date +%y%m%d_%H%M%S)
SCRIPT_NAME="run_${params.run}_mitogenomes_\${TIMESTAMP}.sh"

cat > \$SCRIPT_NAME << "EOF"
#!/usr/bin/env bash
# Auto-generated by the Draft-Genomes TRIGGER_MITOGENOME module for run
# ${params.run}. Everything below the marker is a verbatim copy of the mito
# pipeline's nextflow_run.sh.
#
# Change the OG_* values below for a one-off tweak to this run only.
# Change nextflow_run.sh in the mito repo for anything that should apply to
# every run: it is copied in fresh each time this script is generated.
export RUN_DIR="${params.mitogenome_nfcore_dir}"
export OG_RUN="${params.run}"
export OG_OUT_DIR="/scratch/pawsey1348/\$USER/${params.run}_mitogenomes"
export OG_WORK_DIR="work/${params.run}_mitogenomes"
export OG_LOG_NAME=".nextflow_${params.run}.log"
export OG_INPUT_DIR="${input_pattern}"
export OG_BS_CONFIG="${params.bs_config}"
export OG_SQL_CONFIG="${params.sql_config}"

# ---- copied from ${params.mitogenome_nfcore_dir}/nextflow_run.sh ----
EOF

cat ${mito_launcher} >> \$SCRIPT_NAME

chmod +x \$SCRIPT_NAME
"""
}
