name: bbmap_reformat
description: Remove short contigs from an assembly using BBMap reformat.sh.
keywords:
  - fasta
  - assembly
  - filter
  - bbmap
tools:
  - bbmap:
      description: Suite of bioinformatics tools for manipulating and filtering assemblies and reads.
      homepage: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/
      documentation: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/reformat/
      licence: ["UC-LBL license (see package)"]
      identifier: biotools:bbmap

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'sample', assembly_prefix:'assembly' ]
    - first_filtered_reads:
        type: file
        description: Assembly FASTA file produced by the filtering step.

output:
  - reads:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample', assembly_prefix:'assembly' ]
      - "*.fa":
          type: file
          description: Assembly with contigs shorter than 500 bp removed.
          pattern: "*.fa"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions.
          pattern: "versions.yml"

authors:
  - "@tpeirce"

maintainers:
  - "@tpeirce"
